### ISSUE TITLE
Add download & retainment preferences differentiated by service

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#16]
Presumably, if you have a remote and a local service, you don't want to keep every version of your data on the local system. 

If we implement #10 it would be great if we could specify a config file something like this:

```yaml
services:
    local:
        service: fs.osfs.OSFS
        service_path: '~/my_data_files/'
        retain_versions: 1
        size_warning: 500MB
        size_limit: 5GB

    osdc:
        service: fs.s3fs.S3FS
        service_config: '~/.aws/config'
        bucket: my-data-file
        retain_versions: -1
        size_warning: -1
        size_limit: -1
```
